[profile.default]
solc-version = "0.8.25"
optimizer = true
optimizer-runs = 200
src = "contracts"
out = "artifacts"
libs = ["node_modules", "lib"]
remappings = [
    "@ensdomains/=node_modules/@ensdomains/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "hardhat-deploy/=node_modules/hardhat-deploy/",
    "hardhat/=node_modules/hardhat/",
    "operator-filter-registry/=node_modules/operator-filter-registry/",
    "solady/=node_modules/solady/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
# forge verify-contract \
# --rpc-url https://testnet.skalenodes.com/v1/giant-half-dual-testnet \
# 0x3d1f856a1258FEcd940aCD46b3DF3dCD935b4792 \
# /contracts/nft-with-royalties/factories/NFTFactory.sol:NFTFactory \
# --verifier blockscout \
# --verifier-url https://giant-half-dual-testnet.explorer.testnet.skalenodes.com/api/  